name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://google.com/
          uploadArtifacts: false # save results as an action artifacts
          temporaryPublicStorage: false # upload lighthouse report to the temporary storage
      - name: Run Script
        uses: actions/setup-node@v3
        with:
            node-version: 16
      - run: node src/index.js