name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://google.com/
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: false # upload lighthouse report to the temporary storage
      - name: load 
        id: download
        uses: actions/download-artifact@v3
        with:
          name: 'lighthouse-results'
          path: /home/runner/work/lighthouse-sandbox/lighthouse-sandbox
      - name : Echo download path
        run: echo ${{steps.download.outputs.download-path}}
